# SciPy

In [2]:
import scipy.linalg
import numpy as np

In [24]:
x = np.arange(9).reshape((3,3))
print(x)
if scipy.linalg.det(x):
    print('\n', scipy.linalg.inv(x))
else:
    print('Singular matrix. Cannot compute inverse.')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Singular matrix. Cannot compute inverse.


In [22]:
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(y)
if scipy.linalg.det(y):
    print('\n', scipy.linalg.inv(y))
else:
    print('Singular matrix. Cannot compute inverse.')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Singular matrix. Cannot compute inverse.


In [16]:
y = np.array([[0, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(y)
print('\n', scipy.linalg.inv(y))

[[0 2 3]
 [4 5 6]
 [7 8 9]]

 [[-1.          2.         -1.        ]
 [ 2.         -7.          4.        ]
 [-1.          4.66666667 -2.66666667]]


In [18]:
# ax = b
a = np.array([[2, 1, -3],
              [4, -2, 1],
              [3, 5, -2]])
b = np.array([-4, 9, 5])
x = scipy.linalg.solve(a, b)
print(x)

[2. 1. 3.]


In [26]:
a = np.array([[0, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(scipy.linalg.det(a))
print(scipy.linalg.norm(a))

3.0
16.852299546352718


In [33]:
a = 1 + np.arange(36).reshape(6, 6)
print(a, '\n')
print(scipy.linalg.tril(a, k = 2))
print()
print(scipy.linalg.triu(a, k = -2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]] 

[[ 1  2  3  0  0  0]
 [ 7  8  9 10  0  0]
 [13 14 15 16 17  0]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [ 0 20 21 22 23 24]
 [ 0  0 27 28 29 30]
 [ 0  0  0 34 35 36]]


In [40]:
a = 1 + np.arange(49).reshape(7,7)
print(a, '\n')


p, l, u = scipy.linalg.lu(a)

print('permutation matrix\n', p, '\n')
print('lower component\n', l, '\n')
print('upper component\n', u)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]] 

permutation matrix
 [[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]] 

lower component
 [[ 1.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.02325581  1.          0.          0.          0.          0.
   0.        ]
 [ 0.8372093   0.16666667  1.          0.          0.          0.
   0.        ]
 [ 0.51162791  0.5        -0.          1.          0.          0.
   0.        ]
 [ 0.34883721  0.66666667 -0.          0.          1.          0.
   0.        ]
 [ 0.6744186   0.33333333 -0.          0.          0.          1.
   0.        ]
 [ 0.18604651  0.83333333 -0.          0.5         0.          0.25
   1.        ]] 

upper component
 [[ 4.30000000e+01  4.40000000e+0

In [43]:
a = np.arange(9).reshape(3, 3)
q, r = scipy.linalg.qr(a)
print(q)
print(r)

[[ 4.44089210e-16  1.20402011e+00 -1.88423342e+00]
 [ 0.00000000e+00  6.02010056e-01 -7.04539452e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.22065556e+01]]
[[ 0.40824829 -0.81649658  0.40824829]
 [-0.76923507 -0.06689001  0.63545506]
 [-0.49153915 -0.57346234 -0.65538554]]


In [44]:
a = np.arange(9).reshape(3, 3)
q, r = scipy.linalg.rq(a)
print(q)
print(r)

[[ 4.44089210e-16  1.20402011e+00 -1.88423342e+00]
 [ 0.00000000e+00  6.02010056e-01 -7.04539452e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.22065556e+01]]
[[ 0.40824829 -0.81649658  0.40824829]
 [-0.76923507 -0.06689001  0.63545506]
 [-0.49153915 -0.57346234 -0.65538554]]
